// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfgclitiwjpvolnhkdvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmZ2NsaXRpd2pwdm9sbmhrZHZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MDg1OTEsImV4cCI6MjA3MDM4NDU5MX0.3RzrtPyjUG9qsNXUY9qRzZCNr-3nWFfRo2cUFpVE9oQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});